-- ============================================================================
-- Phase 3.4 (step 5 polish) — Block per-user duplicate workspace names
-- ============================================================================
-- Replaces create_workspace_with_owner with a version that rejects a name
-- the calling user already has on one of their OWNED workspaces. Trim +
-- case-insensitive comparison so "  Acme  ", "Acme", and "acme" all collide.
--
-- Why this gate exists:
--   * Step 5 collision testing surfaced a UX bug — the switcher dropdown
--     rendered two entries both labelled "Test Workspace Two." The
--     auto-suffix slug trigger differentiates URLs cleanly, but the
--     visible label is identical and confuses users into thinking the
--     switcher is broken.
--   * Within a single user's own workspace list, duplicate names are
--     almost always a typo or "did I already create this?" mistake. The
--     auto-suffix should remain a quiet safety net for the cross-user
--     case (two different agencies independently creating "Acme"), not
--     the primary handler for self-collisions.
--
-- Scope of the check (deliberate):
--   * Per-user. Two different users can each name a workspace "Acme."
--     RLS already isolates their data; the slug auto-suffixer handles
--     URL uniqueness silently.
--   * Owned only. Workspaces the user is a member-of-without-owning
--     don't count toward duplicates — those were named by their actual
--     owner.
--   * Case-insensitive + trim-applied. "Acme", "acme", "  Acme  " all
--     match against an existing "Acme."
--
-- This is the SERVER-SIDE BACKSTOP. The form runs the same check client-
-- side before calling the RPC so the user gets immediate feedback without
-- a round-trip. The server check is the defence-in-depth catch for any
-- direct API call bypassing the form.
--
-- Trim behaviour preserved:
--   The existing function already called `trim()` before insert; this
--   migration doesn't change that. The stored `name` column has always
--   had leading/trailing whitespace stripped — confirmed by Step 5's
--   verification SQL.
--
-- ┌─ DOWN PLAN (manual rollback recipe)
-- │
-- │   Re-run the function body from 20260511120000 (without the
-- │   duplicate-name exists() block).
-- │
-- └────────────────────────────────────────────────────────────────────────
-- ============================================================================


create or replace function public.create_workspace_with_owner(workspace_name text)
returns json language plpgsql security definer
set search_path = ''
as $$
declare
  new_workspace_id   uuid;
  new_workspace_slug text;
  cleaned_name       text;
  actor              uuid := (select auth.uid());
begin
  if actor is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  cleaned_name := trim(coalesce(workspace_name, ''));
  if cleaned_name = '' then
    raise exception 'Workspace name cannot be empty'
      using errcode = '22023';
  end if;
  if length(cleaned_name) > 80 then
    raise exception 'Workspace name cannot exceed 80 characters'
      using errcode = '22023';
  end if;

  -- Per-user duplicate check. Comparison is case-insensitive (both sides
  -- lower()-ed) and trim-applied (both sides trimmed) so "Acme" / "acme" /
  -- "  Acme  " all collide. Scoped to workspaces the user owns
  -- (role='owner'); workspaces they're a member-of-without-owning don't
  -- count, since those were named by their actual owner.
  --
  -- SQLSTATE 23505 is unique_violation. Not a true DB-level unique
  -- constraint violation (we don't have one — schema-level uniqueness
  -- across users would be wrong), but the semantic fit is right and
  -- gives clients a recognisable code.
  if exists (
    select 1
    from public.workspace_memberships wm
    join public.workspaces w on w.id = wm.workspace_id
    where wm.user_id = actor
      and wm.role = 'owner'
      and lower(trim(w.name)) = lower(cleaned_name)
  ) then
    raise exception 'You already have a workspace named "%". Pick a different name.', cleaned_name
      using errcode = '23505';
  end if;

  -- Insert workspace. Slug is auto-generated by workspaces_auto_slug
  -- trigger (20260509150000) — still useful for the cross-user case
  -- where two different owners independently pick the same name.
  insert into public.workspaces (name)
  values (cleaned_name)
  returning id, slug into new_workspace_id, new_workspace_slug;

  -- Same transaction as the workspace insert — if this fails the workspace
  -- insert rolls back too.
  insert into public.workspace_memberships (workspace_id, user_id, role)
  values (new_workspace_id, actor, 'owner');

  return json_build_object(
    'id',   new_workspace_id,
    'slug', new_workspace_slug,
    'name', cleaned_name
  );
end;
$$;


-- CREATE OR REPLACE FUNCTION preserves existing grants, but re-issuing is
-- idempotent and makes the migration self-contained.
grant execute on function public.create_workspace_with_owner(text) to authenticated;


-- ============================================================================
-- Verification (run manually after apply)
-- ============================================================================
-- 1. Functional smoke: a duplicate attempt should raise 23505. Replace
--    <UUID> with jordanperez1270's user_id and use a name they already own
--    (e.g. "Test Workspace Two"):
--
--   begin;
--   set local role authenticated;
--   set local request.jwt.claims to '{"sub":"<UUID>","role":"authenticated"}';
--   select public.create_workspace_with_owner('Test Workspace Two');
--   rollback;
--
--   Expected: ERROR 23505 with message
--     'You already have a workspace named "Test Workspace Two". Pick a different name.'
--
-- 2. Case-insensitivity check (same setup):
--   select public.create_workspace_with_owner('test workspace two');
--   Expected: same 23505 error.
--
-- 3. Trim check:
--   select public.create_workspace_with_owner('   Test Workspace Two   ');
--   Expected: same 23505 error.
--
-- 4. Cross-user allowed (impersonate jordan+phasea, who doesn't own
--    "Test Workspace Two"):
--   begin;
--   set local request.jwt.claims to '{"sub":"<phasea-UUID>","role":"authenticated"}';
--   select public.create_workspace_with_owner('Test Workspace Two');
--   rollback;
--   Expected: success, returns a JSON object with a fresh id + auto-
--   suffixed slug (test-workspace-two-N).
-- ============================================================================
