-- ============================================================================
-- Stages — WL-2: auto-create personal workspace on signup
-- ============================================================================
-- Second slice of the workspace-limits (WL) sprint. Extends the
-- handle_new_user trigger function so every successful auth.users
-- INSERT also provisions:
--   * one public.workspaces row (name='Personal', type='personal')
--   * one public.workspace_memberships row binding the new user to
--     that workspace as role='owner'
-- The trigger BINDING (on_auth_user_created AFTER INSERT ON auth.users)
-- is unchanged — only the function body grows.
--
-- DESIGN DECISIONS (locked per WL-sprint audit)
-- ──────────────────────────────────────────────
-- 1. Workspace name = literal 'Personal' for every user.
--    raw_user_meta_data is empty {} for email+password sign-ups, so any
--    "{first name}'s Personal" derivation would NULL-fallback to a
--    generic name anyway. Cleaner to ship one consistent literal and
--    let users rename in settings later.
--
-- 2. Slug auto-generated by the workspaces_auto_slug trigger:
--    'Personal' → 'personal' (first user), 'personal-2' (second), etc.
--    No collision logic needed in this function.
--
-- 3. Workspace type = 'personal'. WT-4's init_workspace_billing trigger
--    already skips type='personal' workspaces, so no workspace_billing
--    row gets created. WL-1's per-user 1-agency cap is unaffected
--    (personal doesn't count against the agency budget).
--
-- 4. DEFENSIVE FAILURE HANDLING — critical for trust in the auth path.
--    The auto-personal logic is wrapped in a nested BEGIN/EXCEPTION
--    WHEN OTHERS block that swallows ANY failure with a RAISE NOTICE
--    and does NOT re-raise. Rationale:
--      * If auto-personal fails for any reason, the auth.users INSERT
--        ITSELF must still succeed — the user can sign up, log in,
--        and create a personal manually via the existing flow.
--      * A user without an auto-personal is a degraded experience;
--        a user who cannot sign up is a broken product.
--      * RAISE NOTICE surfaces the failure in postgres logs for debug
--        without aborting the surrounding transaction.
--    The profile INSERT is NOT wrapped — it's idempotent
--    (on conflict do nothing) and has been in production unchanged
--    since 20260510120000. If it ever fails, that signals a deeper
--    problem we'd want to surface, not swallow.
--
-- 5. IDEMPOTENCY guard before insert: skip silently if the user
--    already owns a personal workspace. Defends against re-fire edge
--    cases (e.g., manual re-invocation, future trigger-binding work).
--    Predicate uses workspace_memberships join, not "any workspaces
--    row I might already own" — that latter check could let a stale
--    orphaned workspaces row block future provisioning.
--
-- 6. NO BACKFILL for existing users. Jordan (the only pre-existing
--    user) already created his personal during WL-1 smoke testing.
--    Other users (none) would need a separate backfill migration if
--    we ever want one — this slice is signup-forward only.
--
-- 7. The profile INSERT remains byte-for-byte identical to its
--    20260510120000 form. Two-key coalesce pattern (full_name/name,
--    avatar_url/picture) for OAuth-provider normalization differences
--    is preserved verbatim. The auto-personal block runs AFTER the
--    profile insert + BEFORE the final `return new` so a downstream
--    consumer of the trigger result sees the NEW row unchanged.
--
-- ─── INTERACTION WITH SIBLING SYSTEMS ───────────────────────────────
-- WL-1 1-agency cap   — unaffected. Personal doesn't count toward agency.
-- WT-4 1-personal cap — unaffected at this entry point. The cap is
--                       enforced inside create_workspace_with_owner;
--                       this trigger bypasses the RPC and inserts
--                       directly. For brand-new signups personal_count
--                       starts at 0, so this is the first (and only)
--                       personal that lands without any cap collision.
--                       If the trigger were ever re-fired against an
--                       existing user with a personal already, the
--                       idempotency guard (#5 above) skips the insert.
-- init_workspace_billing trigger — skips type='personal', so no
--                       workspace_billing row is created. Verified
--                       in WT-4 migration 20260626120000:91.
-- workspaces_auto_slug trigger  — runs on workspaces INSERT, generates
--                       slug from name (collision-suffixed).
-- workspaces_insert_c1_enforcement RESTRICTIVE RLS — bypassed by
--                       SECURITY DEFINER context.
--
-- ─── UX COUPLING FLAGGED FOR WL-3 ───────────────────────────────────
-- Pre-WL-2, the /onboarding/create-workspace selectorMode logic
-- (page.tsx:134-139) treated "zero contexts" as the brand-new-signup
-- case → 'show-with-agency-default'. Post-WL-2, brand-new signups have
-- exactly one personal workspace_membership before they ever reach
-- the form, so summary.hasAgency is true (it counts workspace_-
-- memberships of any type). The form will detect that path and
-- branch differently. WL-3 will adjust the selectorMode logic to
-- recognize "the only context is the auto-created personal" as
-- equivalent to "brand-new" and still default the form to agency.
-- DO NOT fix in WL-2 — this slice is server-only.
--
-- ┌─ DOWN PLAN
-- │
-- │   Restore the pre-WL-2 handle_new_user by CREATE OR REPLACE-ing it
-- │   with the body from 20260510120000_profile_enrichment.sql:85-106.
-- │   The auto-personal block is purely a function-body addition; no
-- │   data needs to revert. Workspaces auto-created BEFORE the revert
-- │   stay; if you want to also remove them, manually:
-- │
-- │     delete from public.workspaces w
-- │     where w.type = 'personal'
-- │       and w.name = 'Personal'
-- │       and exists (
-- │         select 1 from public.workspace_memberships wm
-- │         where wm.workspace_id = w.id
-- │           and wm.role = 'owner'
-- │           and w.created_at >= '<WL-2 apply timestamp>'
-- │       );
-- │
-- │   But take a snapshot first — users actively using their auto-
-- │   personal would be surprised by the delete.
-- │
-- └──────────────────────────────────────────────────────────────────────
-- ============================================================================


create or replace function public.handle_new_user()
returns trigger language plpgsql security definer
set search_path = ''
as $$
declare
  new_personal_ws_id uuid;
begin
  -- ── 1. Profile row (preserved byte-for-byte from 20260510120000) ────
  -- on conflict (id) do nothing — idempotent against trigger re-fire
  -- and against any racy double-INSERT during OAuth identity-link.
  -- Two-key coalesce defends against provider-naming drift (Google
  -- normalizes full_name + picture, but raw fields name + picture are
  -- also present; future providers may use either). NULL fallthrough
  -- is safe — both columns are nullable.
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name'
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture'
    )
  )
  on conflict (id) do nothing;

  -- ── 2. WL-2: auto-create personal workspace ─────────────────────────
  -- Wrapped in a defensive sub-block. If ANYTHING in here errors —
  -- workspaces insert fails, slug-trigger fires an unexpected
  -- exception, FK violation, anything — the EXCEPTION WHEN OTHERS
  -- handler catches it, emits a NOTICE for the postgres logs, and
  -- the surrounding handle_new_user trigger continues to return NEW.
  -- The auth.users INSERT itself commits. Sign-up succeeds even if
  -- personal-workspace creation is broken. The user can create one
  -- manually later via /onboarding/create-workspace.
  --
  -- The idempotency guard (NOT EXISTS check) is structural defense
  -- against re-fire — the AFTER INSERT trigger normally fires exactly
  -- once per row, but manual re-invocation (or future trigger-binding
  -- work) could re-enter here. Skip silently in that case so we don't
  -- pile up duplicate personals or hit the WT-4 1-personal cap.
  begin
    if not exists (
      select 1
      from public.workspace_memberships wm
      join public.workspaces w on w.id = wm.workspace_id
      where wm.user_id = new.id
        and wm.role = 'owner'
        and w.type = 'personal'
    ) then
      -- Slug auto-generated by workspaces_auto_slug trigger. Type
      -- 'personal' triggers init_workspace_billing to skip (WT-4),
      -- so no workspace_billing row gets created here.
      insert into public.workspaces (name, type)
      values ('Personal', 'personal')
      returning id into new_personal_ws_id;

      -- Owner membership in the same logical step (this nested BEGIN
      -- doesn't open a sub-transaction; both inserts share the
      -- enclosing trigger's transaction). If this membership insert
      -- fails post-workspace-insert, the EXCEPTION below catches it
      -- and the workspace row is NOT cleaned up — it becomes a stale
      -- ownerless workspace. Acceptable: stale ownerless workspaces
      -- are harmless (no consumer references them) and the failure
      -- is logged for follow-up. Better than abort-the-signup.
      insert into public.workspace_memberships (workspace_id, user_id, role)
      values (new_personal_ws_id, new.id, 'owner');
    end if;

  exception when others then
    -- Failure swallowed by design (see file header). NOTICE is visible
    -- in postgres logs; surface there for debugging, not in the
    -- caller's error path. SQLERRM carries the underlying message
    -- without the stack.
    raise notice 'handle_new_user: auto-personal creation failed for user %: %', new.id, sqlerrm;
  end;

  return new;
end;
$$;


-- ============================================================================
-- VERIFICATION QUERIES (commented — run in SQL editor after apply)
-- ============================================================================
-- (a) Confirm handle_new_user carries BOTH the profile insert AND the
--     WL-2 auto-personal logic. The text-match looks for distinctive
--     phrases from each block; if either flips to false the migration
--     applied partially.
--   select
--     position('insert into public.profiles' in pg_get_functiondef(oid)) > 0
--       as profile_insert_intact,
--     position('auto-personal creation failed for user' in pg_get_functiondef(oid)) > 0
--       as auto_personal_block_present,
--     position($$values ('Personal', 'personal')$$ in pg_get_functiondef(oid)) > 0
--       as personal_literal_present
--   from pg_proc
--   where pronamespace = 'public'::regnamespace
--     and proname = 'handle_new_user';
--   -- Expected: all three true.
--
-- (b) Confirm the trigger binding is unchanged — still AFTER INSERT on
--     auth.users, still calling handle_new_user.
--   select tgname, tgenabled, tgtype
--   from pg_trigger
--   where tgrelid = 'auth.users'::regclass
--     and tgname = 'on_auth_user_created';
--   -- Expected: 1 row, tgenabled = 'O' (origin = enabled).
--
-- (c) Pre-test snapshot — count Jordan's existing workspaces by type
--     before any signup test. Save these numbers; verification (e) below
--     re-runs and compares.
--   select w.type, count(*) as ws_count
--   from public.workspace_memberships wm
--   join public.workspaces w on w.id = wm.workspace_id
--   where wm.user_id = 'f3d54a29-ad84-4de5-a727-5af825be3206'
--   group by w.type
--   order by w.type;
--   -- Expected (pre-test, post-WL-1): agency=2, personal=1.
--
-- (d) After signing up a throwaway test user via the public form, run
--     these to confirm the trigger fired and produced the expected
--     side-effects. Substitute <throwaway-user-id> with the new user's
--     auth.users.id (Supabase Dashboard → Authentication → Users).
--   select
--     (select count(*) from public.profiles where id = '<throwaway-user-id>')
--       as profile_count,
--     (select count(*) from public.workspaces w
--      join public.workspace_memberships wm on wm.workspace_id = w.id
--      where wm.user_id = '<throwaway-user-id>'
--        and wm.role = 'owner'
--        and w.type = 'personal'
--        and w.name = 'Personal')
--       as personal_workspace_count;
--   -- Expected: profile_count = 1, personal_workspace_count = 1.
--
-- (e) Re-run (c) verbatim. Jordan's counts should be UNCHANGED — the
--     trigger fires only on new auth.users INSERTs, and he existed
--     before the migration applied.
--   -- Expected: agency=2, personal=1 (identical to pre-test).
--
-- (f) Postgres log inspection — if step (d) shows
--     personal_workspace_count = 0, the EXCEPTION block fired. Check
--     Supabase Logs → Postgres for a NOTICE line matching:
--       handle_new_user: auto-personal creation failed for user <uuid>: <reason>
--     That message identifies the failure mode without aborting signup.
-- ============================================================================
