-- ============================================================================
-- Phase 3.4 (step 5) — create_workspace_with_owner RPC
-- ============================================================================
-- Atomically creates a workspace and the creator's owner membership in a
-- single transaction. Both inserts happen inside one PL/pgSQL function body
-- so they share the function's implicit transaction — if the membership
-- insert fails for any reason (FK, constraint, etc.), the workspace insert
-- rolls back too. No orphaned workspaces.
--
-- Why an RPC instead of a BEFORE/AFTER INSERT trigger that auto-owners every
-- workspace:
--   * Explicit at the call site. The app says "create a workspace and make
--     me its owner," not "insert a row and hope a trigger does the right
--     thing." Future maintainers won't be surprised.
--   * Easier to extend. If we ever add an admin-tool flow where someone
--     creates a workspace on behalf of another user, we can do that via
--     a different RPC (or direct INSERT for a system role) without
--     fighting an implicit trigger.
--   * Side-steps the chicken-and-egg with workspace_memberships_insert
--     policy. That policy gates inserts on `is_workspace_owner(workspace_id)` —
--     true for adding teammates to an existing workspace, but false for the
--     creator of a brand-new one (no owner exists yet). The RPC bypasses
--     RLS internally via `security definer` while keeping the policy strict
--     for direct INSERTs from app code.
--
-- Returns a JSON object with id + slug + name so the client can route to
-- /w/[slug] without a second round trip.
--
-- ┌─ DOWN PLAN (manual rollback recipe; Supabase doesn't auto-run a down)
-- │
-- │   revoke execute on function public.create_workspace_with_owner(text)
-- │     from authenticated;
-- │   drop function if exists public.create_workspace_with_owner(text);
-- │
-- └────────────────────────────────────────────────────────────────────────
-- ============================================================================


create or replace function public.create_workspace_with_owner(workspace_name text)
returns json language plpgsql security definer
set search_path = ''
as $$
declare
  new_workspace_id   uuid;
  new_workspace_slug text;
  cleaned_name       text;
  actor              uuid := (select auth.uid());
begin
  -- Authn check. anon role has auth.uid() = null; reject.
  if actor is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  -- Defensive validation. The client validates too, but this is the
  -- backstop for direct SQL/CLI callers and for any future client surfaces.
  cleaned_name := trim(coalesce(workspace_name, ''));
  if cleaned_name = '' then
    raise exception 'Workspace name cannot be empty'
      using errcode = '22023';  -- invalid_parameter_value
  end if;
  if length(cleaned_name) > 80 then
    raise exception 'Workspace name cannot exceed 80 characters'
      using errcode = '22023';
  end if;

  -- Insert workspace. Slug is auto-generated by workspaces_auto_slug
  -- trigger (defined in 20260509150000) — that trigger handles collision
  -- suffixing too, so callers don't need to pre-check.
  insert into public.workspaces (name)
  values (cleaned_name)
  returning id, slug into new_workspace_id, new_workspace_slug;

  -- Insert the owner membership. Same transaction — if this raises, the
  -- workspace insert above rolls back too.
  insert into public.workspace_memberships (workspace_id, user_id, role)
  values (new_workspace_id, actor, 'owner');

  return json_build_object(
    'id',   new_workspace_id,
    'slug', new_workspace_slug,
    'name', cleaned_name
  );
end;
$$;


-- security definer functions need explicit execute grants to the roles that
-- should be allowed to call them. `authenticated` is the role Supabase uses
-- for any signed-in user; anon is excluded (the function would raise on the
-- auth.uid() check anyway, but excluding here is belt-and-suspenders).
grant execute on function public.create_workspace_with_owner(text) to authenticated;


-- ============================================================================
-- Verification (run manually after apply)
-- ============================================================================
-- 1. Confirm the function exists with the right signature + security:
--   select proname, prosecdef, pg_get_function_identity_arguments(oid)
--   from pg_proc
--   where pronamespace = 'public'::regnamespace
--     and proname = 'create_workspace_with_owner';
--   Expected: prosecdef = true, args = "workspace_name text".
--
-- 2. Confirm the authenticated role has execute privilege:
--   select grantee, privilege_type
--   from information_schema.role_routine_grants
--   where routine_schema = 'public'
--     and routine_name = 'create_workspace_with_owner';
--   Expected: row with grantee = 'authenticated', privilege_type = 'EXECUTE'.
--
-- 3. Functional smoke (impersonate a real user — replace UUID):
--   begin;
--   set local role authenticated;
--   set local request.jwt.claims to '{"sub":"<USER_UUID>","role":"authenticated"}';
--   select public.create_workspace_with_owner('Smoke Test Workspace');
--   rollback;
--   Expected: JSON object with id, slug ('smoke-test-workspace' or
--   '-N' suffix), name. Rollback wipes the test rows.
-- ============================================================================
